name: Build and Deploy Angular Native to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read    # Minimum layout access to read codebase
  pages: write       # Essential infrastructure access to modify GitHub Pages
  id-token: write    # OpenID Connect (OIDC) token capability for direct server deployment

concurrency:
  group: "pages"
  cancel-in-progress: true # Cancels old deployments if you push updates rapidly

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rss-angular-viewer
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        id: build_angular
        run:  |
          # Run your normal build command
          npm run build -- --configuration=production
          pwd
          ls -la dist/rss-angular-viewer/browser
          # Step 2: Use standard bash/pwd to find the compiled path dynamically.
          # We search inside the local 'dist' folder for your project name.
          PROJECT_DIST_PATH=$(pwd)/dist/rss-angular-viewer/browser
          echo "Project build path: $PROJECT_DIST_PATH"
          
          # Step 3: Write it to the $GITHUB_OUTPUT environment file
          echo "build_path=${PROJECT_DIST_PATH}" >> $GITHUB_OUTPUT

      - name: Upload Static Website Artifact (Latest v5)
        uses: actions/upload-pages-artifact@v5
        with:
          # Match your exact local Angular 17+ dist output folder path
          path: ${{ steps.build_angular.outputs.build_path }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rss-angular-viewer
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Direct to GitHub Pages Infrastructure (Latest v5)
        id: deployment
        uses: actions/deploy-pages@v5
